apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeSelector:
    app: nginx
  shareProcessNamespace: true
  hostNetwork: true
  hostIPC: true
  #  hostPID: true
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "abc.com"
    - "def.com"
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: busybox
    stdin: true
    tty: true
