apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  nodeSelector:
    app: nginx
  shareProcessNamespace: true
  hostNetwork: true
  hostIPC: true
  #  hostPID: true
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "abc.com"
    - "def.com"
  containers:
  - name: nginx-lifecycle
    image: nginx
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo hello from poststart handler > /root.txt"]
      preStop:
        exec:
          command: ["/usr/sbin/nginx", "-s", "quit"]
  - name: shell
    image: busybox
    stdin: true
    tty: true
